version: '3.8'

# This overrides the base docker-compose.yml for AWS Production using Traefik
services:
  frontend:
    # No exposed ports. Traefik will route traffic to this container's internal port 80.
    networks:
      - traefik-public
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio-frontend.rule=Host(`kravlone.xyz`) || Host(`www.kravlone.xyz`)"
      - "traefik.http.routers.portfolio-frontend.entrypoints=websecure"
      - "traefik.http.routers.portfolio-frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.portfolio-frontend.loadbalancer.server.port=80"

  admin:
    networks:
      - traefik-public
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio-admin.rule=Host(`admin.kravlone.xyz`)"
      - "traefik.http.routers.portfolio-admin.entrypoints=websecure"
      - "traefik.http.routers.portfolio-admin.tls.certresolver=letsencrypt"
      - "traefik.http.services.portfolio-admin.loadbalancer.server.port=80"

networks:
  traefik-public:
    external: true
