"""Add location and date columns

Revision ID: 5c5a97696618
Revises: 7d9534b13188
Create Date: 2026-09-27 21:25:50.283102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c5a97696618'
down_revision: Union[str, None] = '7d9534b13188'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiences', sa.Column('location', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('location', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'date')
    op.drop_column('projects', 'location')
    op.drop_column('experiences', 'location')
    # ### end Alembic commands ###
